version: '3'

services:
  web:
    image: glosseum-api:0.1
    restart:
      always
    ports:
      - "8000:8000"
    environment:
      RDB: postgresql+asyncpg
      DB_HOST: ${DB_HOST}
      DB_PORT: 5432
      DB_NAME: glosseum-dev
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - default

networks:
    default:
