version: '3'

services:
  web:
    image: glosseum-api:0.1
    restart:
      always
    ports:
      - "8000:8000"
    environment:
      RDB: postgresql+asyncpg
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_NAME: glosseum-dev
      DB_USER: junseokang
      DB_PASSWORD:
    networks:
      - default

networks:
    default:
