version: '3'

services:
  web:
    image: invalidid56/glosseum-dev:0.1
    restart:
      always
    ports:
      - "8000:8000"
    environment:
      RDB: postgresql+asyncpg
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB: ${DB}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - default

networks:
    default:
