"""add cascade

Revision ID: 56a3f986a74e
Revises: d9713ebadc3d
Create Date: 2024-01-14 17:04:10.977457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56a3f986a74e'
down_revision: Union[str, None] = 'd9713ebadc3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_article_name', table_name='article')
    op.create_index(op.f('ix_article_name'), 'article', ['name'], unique=False)
    op.drop_constraint('article_board_id_fkey', 'article', type_='foreignkey')
    op.drop_constraint('article_creator_id_fkey', 'article', type_='foreignkey')
    op.create_foreign_key(None, 'article', 'board', ['board_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'article', 'user', ['creator_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index('ix_board_name', table_name='board')
    op.create_index(op.f('ix_board_name'), 'board', ['name'], unique=False)
    op.drop_constraint('board_creator_id_fkey', 'board', type_='foreignkey')
    op.create_foreign_key(None, 'board', 'user', ['creator_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('comment_article_id_fkey', 'comment', type_='foreignkey')
    op.drop_constraint('comment_creator_id_fkey', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'user', ['creator_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'comment', 'article', ['article_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_creator_id_fkey', 'comment', 'user', ['creator_id'], ['id'])
    op.create_foreign_key('comment_article_id_fkey', 'comment', 'article', ['article_id'], ['id'])
    op.drop_constraint(None, 'board', type_='foreignkey')
    op.create_foreign_key('board_creator_id_fkey', 'board', 'user', ['creator_id'], ['id'])
    op.drop_index(op.f('ix_board_name'), table_name='board')
    op.create_index('ix_board_name', 'board', ['name'], unique=True)
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.create_foreign_key('article_creator_id_fkey', 'article', 'user', ['creator_id'], ['id'])
    op.create_foreign_key('article_board_id_fkey', 'article', 'board', ['board_id'], ['id'])
    op.drop_index(op.f('ix_article_name'), table_name='article')
    op.create_index('ix_article_name', 'article', ['name'], unique=True)
    # ### end Alembic commands ###
