name: Lint

on:
  [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint==2.17.4 black==23.3.0
      - name: Analysing the code with pylint
        run: |
          black --check $(git ls-files '*.py')
          pylint $(git ls-files '*.py') || true
