name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          docker build -t glosseum-dev:0.1 .

      - name: Test
        run: |
          export SITE_ENV=test
          
          export DB_HOST=${{ secrets.DB_HOST }}
          export DB_USER=${{ secrets.DB_USER }}
          export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          export DB_PORT=${{ secrets.DB_PORT }}
          export DB=${{ secrets.DB }}
          
          export CREDENTIAL_ALGORITHM=${{ secrets.CREDENTIAL_ALGORITHM }}
          export CREDENTIAL_SECRET=${{ secrets.CREDENTIAL_SECRET }}
          
          docker-compose run \
          --rm \
          --build \
          ./test.sh
