name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest==6.2.5 pytest-cov==3.0.0 pytest-asyncio==0.15.1 alembic==1.7.4
      - name: Test
        run: |
          ./test.sh
